import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, CalendarDays, Car, ChevronRight, CircleHelp, Clock3, CreditCard, HeartHandshake, Home, MapPin, MessageCircle, MoreHorizontal, Navigation, Plus, Search, ShieldCheck, Star, Users, X, Zap } from 'lucide-react';
import './styles.css';

const rides = [
  { id: 1, driver: 'Rahul Kumar', initials: 'RK', college: 'ARKA Jain University', rating: '4.8', trips: 24, from: 'Mango', to: 'Bistupur', time: '8:30 AM', seats: 2, cost: 42, match: 94, pickup: '0.6 km away', car: 'Maruti Swift', color: 'orange' },
  { id: 2, driver: 'Ananya Singh', initials: 'AS', college: 'XLRI Jamshedpur', rating: '4.9', trips: 18, from: 'Sakchi', to: 'Bistupur', time: '8:45 AM', seats: 3, cost: 38, match: 89, pickup: '1.1 km away', car: 'Hyundai i20', color: 'purple' },
  { id: 3, driver: 'Arjun Mehta', initials: 'AM', college: 'NIT Jamshedpur', rating: '4.7', trips: 11, from: 'Kadma', to: 'Bistupur', time: '8:20 AM', seats: 1, cost: 45, match: 82, pickup: '1.9 km away', car: 'Tata Nexon', color: 'blue' }
];

function Badge({ children, kind = 'green' }) { return <span className={'badge ' + kind}><ShieldCheck size={12}/>{children}</span> }
function Avatar({ initials, color='orange', small=false }) { return <div className={'avatar '+color+(small?' small':'')}>{initials}</div> }
function Route({ from, to, compact=false }) { return <div className={'route '+(compact?'compact':'')}><span className="dot start"></span><div><b>{from}</b><small>Pickup point</small></div><span className="route-line"></span><span className="dot end"></span><div><b>{to}</b><small>Destination</small></div></div> }

function SearchPanel({onSearch}) { const [from,setFrom]=useState('Mango'); const [to,setTo]=useState('Bistupur'); return <section className="search-panel"><div className="search-head"><div><p className="eyebrow">PLAN A RIDE</p><h2>Where are you going?</h2></div><button className="icon-button"><Navigation size={19}/></button></div><div className="location-input"><MapPin size={19}/><input aria-label="Starting location" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="location-input"><MapPin size={19}/><input aria-label="Destination" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="input-row"><button><CalendarDays size={17}/> Tomorrow <ChevronRight size={15}/></button><button><Clock3 size={17}/> 8:00 – 9:00 <ChevronRight size={15}/></button></div><button className="primary full" onClick={()=>onSearch(from,to)}><Search size={18}/> Find a ride</button></section> }

function RideCard({ride,onRequest}) { return <article className="ride-card"><div className="ride-top"><div className="driver"><Avatar initials={ride.initials} color={ride.color}/><div><h3>{ride.driver}</h3><p><Star size={13} fill="currentColor"/> {ride.rating} · {ride.trips} rides</p></div></div><span className="match"><Zap size={13} fill="currentColor"/> {ride.match}% match</span></div><Route from={ride.from} to={ride.to} compact/><div className="ride-meta"><span><Clock3 size={15}/>{ride.time}</span><span><Car size={16}/>{ride.car}</span><span><Users size={16}/>{ride.seats} seats</span></div><div className="verified"><Badge>Identity</Badge><Badge>College</Badge><Badge>Vehicle</Badge></div><div className="card-footer"><div><small>Suggested contribution</small><strong>₹{ride.cost}</strong></div><button className="outline" onClick={()=>onRequest(ride)}>Request ride</button></div></article> }

function HomeScreen({setTab,onSearch}) { return <><header className="topbar"><div><p className="muted">Saturday, 19 September</p><h1>Good morning, Yuvraj <span>👋</span></h1></div><button className="notification"><Bell size={19}/><i></i></button></header><SearchPanel onSearch={onSearch}/><section className="quick-grid"><button onClick={()=>setTab('offer')} className="quick-card offer"><span className="quick-icon"><Car size={23}/></span><div><b>Offer a ride</b><small>Share your journey</small></div><ChevronRight size={18}/></button><button onClick={()=>setTab('safety')} className="quick-card safety"><span className="quick-icon"><ShieldCheck size={23}/></span><div><b>Safety Center</b><small>Travel with confidence</small></div><ChevronRight size={18}/></button></section><section className="section"><div className="section-head"><div><p className="eyebrow">UP NEXT</p><h2>Your upcoming ride</h2></div><button className="text-button" onClick={()=>setTab('rides')}>See all</button></div><div className="upcoming"><div className="date-tile"><b>20</b><span>SEP</span></div><div className="upcoming-info"><h3>Mango <span>→</span> Bistupur</h3><p><Clock3 size={14}/> Tomorrow · 8:30 AM</p><p><Avatar initials="RK" small/> Rahul Kumar · Swift</p></div><ChevronRight size={20}/></div></section><section className="impact"><div className="impact-icon">🌱</div><div><p className="eyebrow">YOUR IMPACT</p><h3>12 shared rides</h3><p>You’ve helped avoid an estimated <b>18 kg CO₂</b>.</p></div><button><ChevronRight size={19}/></button></section></> }

function FindScreen({query,onRequest}) { const [verified,setVerified]=useState(false); const shown = useMemo(()=>verified?rides.filter(r=>r.match>85):rides,[verified]); return <><header className="screen-title"><button className="back"><ChevronRight size={22}/></button><div><p className="eyebrow">RIDES FOR YOU</p><h1>{query.from} <span>→</span> {query.to}</h1><p className="muted">Tomorrow · 8:00 – 9:00 AM</p></div></header><div className="filter-row"><button className="filter active">Best match</button><button className="filter">Departure time</button><button className={'filter '+(verified?'active':'')} onClick={()=>setVerified(!verified)}><ShieldCheck size={14}/> Verified only</button><button className="filter"><MoreHorizontal size={17}/></button></div><p className="result-count">{shown.length} rides match your route</p><div className="ride-list">{shown.map(r=><RideCard key={r.id} ride={r} onRequest={onRequest}/>)}</div></> }

function OfferScreen({onPublish}) { const [seats,setSeats]=useState(2); const [step,setStep]=useState(0); const cost = 126 + Math.max(0,seats-1)*4; return <><header className="screen-title plain"><div><p className="eyebrow">OFFER A RIDE</p><h1>Share your journey</h1><p className="muted">Only verified drivers can publish rides.</p></div></header><div className="progress"><i className={step>=0?'done':''}></i><i className={step>=1?'done':''}></i><i className={step>=2?'done':''}></i></div><section className="form-card"><label>YOUR ROUTE</label><div className="location-input"><MapPin size={19}/><input defaultValue="Mango"/></div><div className="location-input"><MapPin size={19}/><input defaultValue="Bistupur"/></div><button className="add-stop"><Plus size={16}/> Add an optional stop</button><div className="input-row"><button><CalendarDays size={17}/> Tomorrow</button><button><Clock3 size={17}/> 8:30 AM</button></div><label>AVAILABLE SEATS</label><div className="seat-picker"><button onClick={()=>setSeats(Math.max(1,seats-1))}>−</button><b>{seats}</b><button onClick={()=>setSeats(Math.min(6,seats+1))}>+</button><span>passengers</span></div></section><section className="contribution"><div className="contrib-head"><div><p className="eyebrow">TRANSPARENT COST SHARE</p><h3>Suggested contribution</h3></div><span>₹{Math.round(cost/(seats+1))}<small>/ passenger</small></span></div><div className="calc-row"><span>Estimated journey · 18.4 km</span><b>₹{cost}</b></div><div className="calc-row"><span>{seats} passengers + you share equally</span><b>₹{Math.round(cost/(seats+1))} each</b></div><button className="learn">How we calculate this <ChevronRight size={15}/></button></section><button className="primary sticky" onClick={()=>onPublish(seats)}>Publish ride <ChevronRight size={18}/></button></> }

function MyRides({setTab}) { const [filter,setFilter]=useState('Upcoming'); return <><header className="screen-title plain"><div><p className="eyebrow">MY JOURNEYS</p><h1>Your rides</h1></div></header><div className="tabs">{['Upcoming','Active','Completed','Cancelled'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{filter==='Upcoming'?<div className="my-ride"><span className="ride-status">UPCOMING</span><Route from="Mango" to="Bistupur"/><div className="ride-details"><span><CalendarDays size={16}/> Sun, 20 Sep</span><span><Clock3 size={16}/> 8:30 AM</span></div><div className="driver-strip"><Avatar initials="RK" small/><div><b>Rahul Kumar</b><small>Maruti Swift · •••• 1234</small></div><Badge>Verified</Badge></div><div className="action-row"><button onClick={()=>setTab('safety')}><ShieldCheck size={17}/> Safety</button><button><MessageCircle size={17}/> Chat</button><button className="danger"><X size={17}/> Cancel</button></div></div>:<div className="empty"><Car size={34}/><h3>No {filter.toLowerCase()} rides</h3><p>Your {filter.toLowerCase()} trips will show up here.</p></div>}</> }

function Profile() { return <><header className="screen-title plain"><div><p className="eyebrow">YOUR PROFILE</p><h1>Account & trust</h1></div><button className="icon-button"><MoreHorizontal size={20}/></button></header><section className="profile-hero"><Avatar initials="YS" color="blue"/><div><h2>Yuvraj Sambhav</h2><p>ARKA Jain University · Jamshedpur</p><div><Badge>Phone verified</Badge><Badge>College verified</Badge></div></div><button className="edit">Edit</button></section><section className="trust-card"><p className="eyebrow">TRUST PROFILE</p><div className="trust-score"><b>4.9</b><div><span><Star size={16} fill="currentColor"/><Star size={16} fill="currentColor"/><Star size={16} fill="currentColor"/><Star size={16} fill="currentColor"/><Star size={16} fill="currentColor"/></span><p>Based on 12 completed rides</p></div></div><div className="trust-grid"><div><b>96%</b><small>Ride completion</small></div><div><b>12</b><small>Shared rides</small></div><div><b>Sep ’25</b><small>Member since</small></div></div></section><section className="settings"><button><ShieldCheck/> Verification & safety <ChevronRight/></button><button><CreditCard/> Contribution payments <ChevronRight/></button><button><CircleHelp/> Help & support <ChevronRight/></button></section></> }

function Safety() { return <><header className="screen-title plain"><div><p className="eyebrow">TRAVEL SAFELY</p><h1>Safety Center</h1><p className="muted">You’re in control throughout your ride.</p></div></header><section className="safety-hero"><ShieldCheck size={34}/><h2>Need urgent help?</h2><p>Contact local emergency services immediately if you’re in danger.</p><button>Emergency contacts</button></section><section className="safety-list"><button><span className="s-icon share"><Navigation/></span><div><b>Share your trip</b><small>Send live trip details to a trusted contact</small></div><ChevronRight/></button><button><span className="s-icon report"><HeartHandshake/></span><div><b>Report a concern</b><small>Unsafe driving, harassment, fraud or more</small></div><ChevronRight/></button><button><span className="s-icon block"><X/></span><div><b>Blocked users</b><small>Manage people you don’t want to connect with</small></div><ChevronRight/></button></section><p className="privacy-note"><ShieldCheck size={14}/> Your precise location is only shared when necessary for an accepted or active ride.</p></> }

function RequestModal({ride,onClose}) { const [done,setDone]=useState(false); if(done) return <div className="modal-bg"><div className="modal success"><div className="check">✓</div><h2>Request sent!</h2><p>{ride.driver} will be notified. You’ll receive an update as soon as they respond.</p><button className="primary full" onClick={onClose}>Done</button></div></div>; return <div className="modal-bg"><div className="modal"><button className="close" onClick={onClose}><X/></button><p className="eyebrow">REQUEST RIDE</p><h2>Join {ride.driver}'s ride?</h2><div className="modal-route"><Route from={ride.from} to={ride.to} compact/></div><div className="request-total"><span>Suggested contribution</span><b>₹{ride.cost}</b><small>Pay directly by Cash or UPI after the ride.</small></div><p className="disclaimer"><ShieldCheck size={15}/> This is a cost share, not a fare. Your request is subject to driver approval.</p><button className="primary full" onClick={()=>setDone(true)}>Send request</button></div></div> }

function App(){ const [tab,setTab]=useState('home'); const [query,setQuery]=useState({from:'Mango',to:'Bistupur'}); const [request,setRequest]=useState(null); const [toast,setToast]=useState(''); const search=(from,to)=>{setQuery({from,to});setTab('find')}; const publish=(seats)=>{setToast(`Ride published with ${seats} available seats`);setTab('rides');setTimeout(()=>setToast(''),3000)}; let content=tab==='home'?<HomeScreen setTab={setTab} onSearch={search}/>:tab==='find'?<FindScreen query={query} onRequest={setRequest}/>:tab==='offer'?<OfferScreen onPublish={publish}/>:tab==='rides'?<MyRides setTab={setTab}/>:tab==='profile'?<Profile/>:<Safety/>; return <main><div className="app-shell"><div className="brand"><span><Car size={19}/></span><b>RideMate</b><em>beta</em></div><div className="content">{content}</div><nav>{[['home',Home,'Home'],['find',Search,'Find ride'],['offer',Plus,'Offer'],['rides',CalendarDays,'My rides'],['profile',Users,'Profile']].map(([id,Icon,label])=><button key={id} className={tab===id?'current':''} onClick={()=>setTab(id)}><span><Icon size={20}/></span><small>{label}</small></button>)}</nav></div>{request&&<RequestModal ride={request} onClose={()=>setRequest(null)}/>} {toast&&<div className="toast"><ShieldCheck size={18}/>{toast}</div>}</main> }
createRoot(document.getElementById('root')).render(<App/>);
